repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: trailing-whitespace

- repo: https://github.com/golangci/golangci-lint
  rev: v1.55.2
  hooks:
    - id: golangci-lint

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.37.0
  hooks:
    - id: markdownlint
